# Project Settings
project_name: "DeepClassifier"
experiment_name: "Arabic_Text_Classification"

# Paths
data:
  raw_path: "experiments/dataset_versions/classfiy_data_v0.csv"
  processed_v1: "experiments/dataset_versions/processed_data_v1.csv"
  model_save_path: "experiments/models_versions/complexity_models_v1/checkpoints/"
  target: "intent"

# Model Hyperparameters
model:
  name: "experiments/models_versions/complexity_bert_v0"
  tokenizer: "aubmindlab/bert-base-arabertv02"
  num_classes: 10
  max_length: 128
  batch_size: 16
  learning_rate: 2e-5
  epochs: 5
  dropout: 0.3
  hidden_dim: 128

  train_val_split: 0.8

# MLflow
mlflow:
  tracking_uri: "http://localhost:5000"
  db_path: "mlruns.db"
