# Project Settings
project_name: "DeepClassifier"
experiment_name: "Arabic_Text_Classification"

# Paths
data:
  raw_path: "experiments/dataset/classfiy_data.csv"
  processed: "experiments/dataset/processed_data.csv"
  model_save_path: "experiments/models/checkpoints/"
  target: "intent"

# Model Hyperparameters
model:
  base_model: "experiments/bert"
  tokenizer: "experiments/bert"
  num_classes: 10
  max_length: 128
  batch_size: 16
  learning_rate: 2e-5
  epochs: 5
  dropout: 0.3
  hidden_dim: 128

  train_val_split: 0.8
  fine_tune: False
# MLflow
mlflow:
  tracking_uri: "http://localhost:5000"
  db_path: "mlruns.db"
