# Project Settings
project_name: "DeepClassifier"
experiment_name: "Arabic_Text_Classification"

# Paths
data:
  raw_path: "experiments/dataset_versions/classfiy_data_v0.csv"
  processed: "experiments/dataset_versions/processed_data_v2.csv"
  model_save_path: "experiments/models_versions/intent_models_v3/checkpoints/"
  target: "intent"

# Model Hyperparameters
model:
  base_model: "experiments/models_versions/intent_models_v2/checkpoints/bert_model"
  head_model: "experiments/models_versions/intent_models_v2/checkpoints/full_model.pth"
  tokenizer: "experiments/models_versions/intent_models_v2/checkpoints/bert_model"
  
  num_classes: 10
  max_length: 128
  batch_size: 16
  learning_rate: 2e-5
  epochs: 5
  dropout: 0.3
  hidden_dim: 128

  train_val_split: 0.8
  fine_tune: True
# MLflow
mlflow:
  tracking_uri: "http://localhost:5000"
  db_path: "mlruns.db"
